/* 
* Copyright (c) 2013, Nordic Semiconductor ASA
* All rights reserved.
* 
* Redistribution and use in source and binary forms, with or without modification,
* are permitted provided that the following conditions are met:
* 
* - Redistributions of source code must retain the above copyright notice, this
*   list of conditions and the following disclaimer.
* 
* - Redistributions in binary form must reproduce the above copyright notice, this
*   list of conditions and the following disclaimer in the documentation and/or
*   other materials provided with the distribution.
* 
* - The name of Nordic Semiconductor ASA may not be used to endorse or promote
*   products derived from this software without specific prior written permission.
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
* ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
* This file is autogenerated by nRFgo Studio 1.16.1.3119
*/

#include "services.h"
#include "lib_aci.h"

static bool is_gap_device_name_set_requested = false;
static bool is_device_information_hardware_revision_string_set_requested = false;
static bool is_uart_over_btle_uart_tx_send_requested = false;

static void *gap_device_name_set;
static uint8_t gap_device_name_set_size;
static void *device_information_hardware_revision_string_set;
static uint8_t device_information_hardware_revision_string_set_size;
static void *uart_over_btle_uart_tx_tx;
static uint8_t uart_over_btle_uart_tx_tx_size;

static bool gap_device_name_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_GAP_DEVICE_NAME_SET, (void*)gap_device_name_set, gap_device_name_set_size));
}

void services_set_gap_device_name(void *src, int size)
{
  gap_device_name_set_size = size;
  gap_device_name_set = src;
  is_gap_device_name_set_requested = true;
  services_update_pipes();
}
static bool device_information_hardware_revision_string_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_DEVICE_INFORMATION_HARDWARE_REVISION_STRING_SET, (void*)device_information_hardware_revision_string_set, device_information_hardware_revision_string_set_size));
}

void services_set_device_information_hardware_revision_string(void *src, int size)
{
  device_information_hardware_revision_string_set_size = size;
  device_information_hardware_revision_string_set = src;
  is_device_information_hardware_revision_string_set_requested = true;
  services_update_pipes();
}
static bool uart_over_btle_uart_tx_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_UART_OVER_BTLE_UART_TX_TX))
  {
    return(lib_aci_send_data(PIPE_UART_OVER_BTLE_UART_TX_TX, (void*)uart_over_btle_uart_tx_tx, uart_over_btle_uart_tx_tx_size));
  }
  return(false);
}

bool services_send_uart_over_btle_uart_tx(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_uart_over_btle_uart_tx_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_uart_over_btle_uart_tx_send_requested)
    {
      uart_over_btle_uart_tx_tx_size = size;
      uart_over_btle_uart_tx_tx = src;
      is_uart_over_btle_uart_tx_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    uart_over_btle_uart_tx_tx_size = size;
    uart_over_btle_uart_tx_tx = src;
    is_uart_over_btle_uart_tx_send_requested = true;
    services_update_pipes();
    return(true);
  }
}

void services_update_pipes(void)
{
  if(is_gap_device_name_set_requested)
  {
    is_gap_device_name_set_requested = !(gap_device_name_update_set());
  }
  if(is_device_information_hardware_revision_string_set_requested)
  {
    is_device_information_hardware_revision_string_set_requested = !(device_information_hardware_revision_string_update_set());
  }
  if(is_uart_over_btle_uart_tx_send_requested)
  {
    is_uart_over_btle_uart_tx_send_requested = !(uart_over_btle_uart_tx_update_send());
  }
}

